import Head from "next/head";
import { useAuth } from "../context/AuthContext";
import OnboardingPage from "./OnboardingPage";
import Dashboard from "./dashboard.js";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth, db } from "../firebase";
import Layout from "../Components/layouts";
import { fetchUser } from "../Store";
import { useEffect } from "react";

const Home = () => {
  const [user] = useAuthState(auth);

  return (
    <div>
      <Head>
        <title>Task management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/https://icons8.com/icon/qmqQkQjR7JHk/citrus" />
      </Head>
      {user ? <Dashboard /> : <OnboardingPage />}
    </div>
  );
};

export default Home;
